version: '3.8'

services:
  telegrambot:
    build: .
    container_name: telegrambot
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
      - ./data:/app/data
      - ./logs:/app/logs
    # Entrypoint handles permissions automatically
    environment:
      - TZ=UTC
    labels:
      - "com.example.service=telegrambot"
      - "com.example.version=1.0"
    healthcheck:
      test: ["CMD", "pgrep", "main"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Uncomment to limit resources
    # deploy:
    #   resources:
    #     limits:
    #       memory: 256M
    #       cpus: '0.5'
    #     reservations:
    #       memory: 128M
    #       cpus: '0.25'
    
    # Uncomment for logging configuration
    # logging:
    #   driver: json-file
    #   options:
    #     max-size: "10m"
    #     max-file: "3"

# Uncomment to use external network
# networks:
#   default:
#     external: true
#     name: bot-network

# Uncomment for external volumes
# volumes:
#   bot-data:
#     external: true 